INSERT INTO Menu (item_name, category, price) VALUES
('Garlic Bread', 'Starters', 5.99),
('Bruschetta', 'Starters', 6.99),
('Stuffed Mushrooms', 'Starters', 7.99),
('Caesar Salad', 'Starters', 6.49),
('Tomato Basil Soup', 'Starters', 5.49),
('Mozzarella Sticks', 'Starters', 6.99),
('Chicken Wings', 'Starters', 8.99),
('Spinach Artichoke Dip', 'Starters', 7.49),
('Shrimp Cocktail', 'Starters', 9.99),
('Caprese Salad', 'Starters', 7.49),
('French Onion Soup', 'Starters', 6.49),
('Deviled Eggs', 'Starters', 5.99),
('Calamari', 'Starters', 8.99),
('Meatballs', 'Starters', 7.99),
('Cheese Platter', 'Starters', 9.49),
('Grilled Salmon', 'Mains', 15.99),
('Ribeye Steak', 'Mains', 19.99),
('Chicken Alfredo', 'Mains', 13.99),
('Veggie Burger', 'Mains', 12.49),
('Spaghetti Bolognese', 'Mains', 14.49),
('BBQ Ribs', 'Mains', 16.99),
('Margherita Pizza', 'Mains', 11.99),
('Beef Tacos', 'Mains', 13.49),
('Shrimp Scampi', 'Mains', 15.49),
('Lamb Chops', 'Mains', 18.99),
('Chicken Parmesan', 'Mains', 14.99),
('Vegan Stir Fry', 'Mains', 12.99),
('Lobster Tail', 'Mains', 24.99),
('Pork Chops', 'Mains', 15.99),
('Turkey Sandwich', 'Mains', 11.49),
('French Fries', 'Sides', 3.99),
('Mashed Potatoes', 'Sides', 4.49),
('Steamed Broccoli', 'Sides', 3.99),
('Coleslaw', 'Sides', 2.99),
('Onion Rings', 'Sides', 4.99),
('Garden Salad', 'Sides', 3.49),
('Baked Beans', 'Sides', 2.99),
('Rice Pilaf', 'Sides', 3.49),
('Grilled Asparagus', 'Sides', 4.49),
('Mac and Cheese', 'Sides', 4.99),
('Sweet Potato Fries', 'Sides', 4.49),
('Corn on the Cob', 'Sides', 2.99),
('Garlic Mashed Potatoes', 'Sides', 4.99),
('Sautéed Spinach', 'Sides', 4.49),
('Hush Puppies', 'Sides', 3.99),
('Chocolate Cake', 'Desserts', 6.99),
('Cheesecake', 'Desserts', 7.49),
('Apple Pie', 'Desserts', 5.99),
('Tiramisu', 'Desserts', 6.99),
('Ice Cream Sundae', 'Desserts', 5.49),
('Creme Brulee', 'Desserts', 7.99),
('Brownie', 'Desserts', 4.99),
('Panna Cotta', 'Desserts', 6.99),
('Fruit Salad', 'Desserts', 4.49),
('Lemon Tart', 'Desserts', 5.99),
('Eclair', 'Desserts', 5.49),
('Red Velvet Cake', 'Desserts', 6.99),
('Key Lime Pie', 'Desserts', 5.99),
('Profiteroles', 'Desserts', 6.49),
('Banana Split', 'Desserts', 5.99),
('Lemonade', 'Drinks', 2.99),
('Iced Tea', 'Drinks', 2.99),
('Cola', 'Drinks', 1.99),
('Orange Juice', 'Drinks', 3.49),
('Espresso', 'Drinks', 2.49),
('Cappuccino', 'Drinks', 3.99),
('Milkshake', 'Drinks', 4.99),
('Smoothie', 'Drinks', 4.49),
('Sparkling Water', 'Drinks', 2.49),
('Red Wine', 'Drinks', 5.99),
('White Wine', 'Drinks', 5.99),
('Craft Beer', 'Drinks', 4.99),
('Margarita', 'Drinks', 6.99),
('Martini', 'Drinks', 7.49),
('Mojito', 'Drinks', 6.49);

SELECT * FROM menu ORDER BY item_id ASC;